# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  up-to-chapter-6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run up to chapter 6
        run: ./build-1-host.sh
      - name: Upload Docker image as build artifact
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "dlfs-1-host:latest"

  chapter-7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Download Docker image build artifact
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "dlfs-1-host:latest"
      - name: Run chapter 7
        run: ./build-2-chroot.sh
