# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  before-gcc-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Remove Android and .NET to increase space on VM
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet
      - name: Run up to GCC tests
        run: ./build-1-host.sh
      - name: Upload Docker image as build artifact
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "dlfs-1-host:latest"

  # gcc-tests:
  #   runs-on: ubuntu-latest
  #   needs: before-gcc-tests
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v2
  #     - name: Remove Android and .NET to increase space on VM
  #       run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet
  #     - name: Download Docker image build artifact
  #       uses: ishworkh/docker-image-artifact-download@v1
  #       with:
  #         image: "dlfs-1-host:latest"
  #     - name: Run GCC tests
  #       run: ./build-2-chroot.sh
  #     - name: Upload Docker image as build artifact
  #       uses: ishworkh/docker-image-artifact-upload@v1
  #       with:
  #         image: "dlfs-1-host:latest"

  after-gcc-tests:
    runs-on: ubuntu-latest
    needs: before-gcc-tests
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Remove Android and .NET to increase space on VM
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet
      - name: Download Docker image build artifact
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "dlfs-1-host:latest"
      - name: Run steps after GCC tests
        run: ./build-3-chroot.sh
      - name: Upload Docker image as build artifact
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "dlfs-1-host:latest"
